#include "cmd_teacher_switch_to_history_board.h"

PROTO_NAMESPACE_BEGIN

IMPLEMENT_COMMAND_RUNTIME_INFO(CommandType::TeacherSwitchToHistoryBoard, CmdTeacherSwitchToHistoryBoard, CommandCell)

PROTO_NAMESPACE_END