#include "cmd_teacher_update_auto_taking_pieces.h"

PROTO_NAMESPACE_BEGIN

IMPLEMENT_COMMAND_RUNTIME_INFO(CommandType::TeacherUpdateAutoTakingPieces, CmdTeacherUpdateAutoTakingPieces, CommandCell)

PROTO_NAMESPACE_END